service:
  golangci-lint-version: 1.60.3

run:
  timeout: 2m

linters-settings:
  govet:
    shadow: true
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  revive:
    min-confidence: 0.1
    rules:
      # Add more comments for exported functions and remove this rule
      - name: package-comments
        disabled: true

linters:
  enable:
    - bodyclose
    - revive
    - govet
    - unconvert
    - gocyclo
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - copyloopvar
    - nakedret
    - gosimple
    - prealloc
    - goimports
    - gofmt
    - errcheck
    - staticcheck

    ## format - fill free to fix
  #    - errcheck
  #    - gofmt
  fast: false
  disable:
    - dupl

issues:
  exclude-rules:
    #    - Fix and remove
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    #    - Fix and remove
    - text: "package-comments: should have a package comment"
      linters:
        - revive
    - text: "shadow: declaration of \"err\" shadows declaration"
      linters:
        - govet
    - path: _test\.go
      linters:
        - gosec
        - dupl
  exclude-use-default: false
