version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - gochecknoinits
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    # - revive
    - staticcheck
    - unconvert
    - unparam
    - govet
    - ineffassign
    - errcheck
  disable:
    - dupl
    - revive # Fix comments latet and re-enable
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    lll:
      line-length: 140
    misspell:
      locale: US
    staticcheck:
      checks: ["all", "-QF1008"]
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration'
      - linters:
          - dupl
          - gosec
        path: _test\.go

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      
