name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: install golangci-lint
        run:
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.60.3
      - name: lint
        run: |
          go version
          $GITHUB_WORKSPACE/golangci-lint version
          $GITHUB_WORKSPACE/golangci-lint --config .golangci.yml run
